version: '3'
services:
  demo:
    image: springboot/doodle_demo
    container_name: springboot_doodle
    ports:
        - 8080:8080
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo:latest
    container_name: doodle_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    
  
      


